// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osujhceeunwpubblsvdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdWpoY2VldW53cHViYmxzdmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODU2NTAsImV4cCI6MjA2MDM2MTY1MH0._C5122TPLG-UWX8zXG1o-r-0g9G9tSmvTtCeA12Cx0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);